config/routes.rb
Rails.application.routes.draw do
  get 'lists/index'
  get 'lists/show'
  get 'lists/new'
  get 'lists/create'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  root to: "lists#index"
  resources :lists, only: [:index, :new, :show,  :create] do
    resources :bookmarks, only: [:new, :create]
  end
  resources :bookmarks, only: [:destroy]


  # get "lists", to: "lists#index"
  # get "list/new", to: "lists#new", as: "new_list"
  # post "lists", to: "lists#create"
  # get"list/:id", to: "lists/show", as: "list"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6}
  validates :movie, uniqueness: { scope: :list,
    message: "You already bookmarked this movie in another list."
  }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  has_one_attached :picture

  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, presence: true
  validates :title, uniqueness: true
  validates :overview, presence: true
  validates :overview, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_bookmark, only: [:destroy]

  def index
    @bookmarks = Bookmark.all
  end

  # def show
  #   @bookmark = Bookmark.find(params[:id])
  # end

  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    # raise
    @bookmark = Bookmark.new(bookmark_params)
    @list = List.find(params[:list_id])
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark.destroy
    redirect_to list_path(@bookmark.list), status: :see_other
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end

  def set_bookmark
    @bookmark = Bookmark.find(params[:id])
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show]

  def index
    @lists = List.all
  end

  def show
    @bookmark = Bookmark.new
    @url = "https://image.tmdb.org/t/p/w500/"
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render "lists/new", status:	:unprocessable_entity
    end
  end

  private

  def list_params
    params.require(:list).permit(:name, :picture)
  end

  def set_list
    @list = List.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/_form.html.erb
<div class="container m-2 p-2">
  <%= simple_form_for([@list, @bookmark]) do |f| %>
    <%= f.association :movie %>
    <%= f.input :comment %>
    <%= f.submit %>
  <% end %>
</div>

app/views/bookmarks/new.html.erb
<%= render "form" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchlist</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body class="text-bg-primary">
    <nav class="d-flex">
      <div class="text-center align-self-center">
        <%= link_to "_movie_night", lists_path, class: "jacquard-24-regular p-3 title" %>
      </div>
    </nav>
    <%= yield %>
    <footer class="text-center m-3">
      <span>Coded with [heart] by Damien</span>
    </footer>
  </body>
</html>

app/views/lists/index.html.erb
<div class="container bg-dark p-3 rounded-3">
  <h2 class="m-2">_your lists</h2>
  <%= link_to "Add a new list", new_list_path, class: "btn btn-secondary m-3" %>
  <div class="container row justify-content-between gap-1 w-100">
    <% @lists.each do |l| %>
      <div class="card col-3 rounded-2 text-bg-tertiary d-flex flex-column justify-content-between">
        <div>
          <% if l.picture.attached? %>
            <%= cl_image_tag l.picture.key, width: 240, height: 200, crop: :auto %>
          <% else %>
            <%= image_tag 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTPQDYau3Hs4-xw1i8jVSUY4BlF4FLmg8lQqg&usqp=CAU' %>
          <% end %>
        </div>
        <div>
          <h4 class="my-3"><%= l.name %></h4>
          <ol>
            <% l.movies[0..4].each do |m| %>
              <li><%= m.title %></li>
            <% end %>
            <span>. . .</span>
          </ol>
        </div>
        <%= link_to 'See more...', list_path(l), class: "btn btn-secondary mb-2" %>
      </div>
    <% end %>
  </div>
</div>

app/views/lists/new.html.erb
<div class="container">
  <%= simple_form_for @list do |f| %>
    <%= f.input :name %>
    <%= f.input :picture, as: :file %>
    <%= f.submit %>
  <% end %>
</div>

app/views/lists/show.html.erb
<div class="container bg-dark p-3 rounded-3">
  <h2><%= @list.name %></h2>
  <div>
    <p class="p-2">Add a new bookmark: </p>
    <div class="row justify-content-center gap-2">
      <% @list.bookmarks.each do |b| %>
        <div class="card col-lg-3 col-md-4 col-sm-9 p-0 rounded-3">
          <img
                    src= <%= "#{@url}#{b.movie.poster_url}" %>
                    alt= <%= b.movie.title %>
                    class="m-0 rounded-3"
              >
            <div class="d-flex flex-column justify-content-between p-1">
              <div class="m-2">
                <p class="fs-5"><%= b.movie.title %></p>
                <%= b.movie.overview %>
              </div>
              <div>
                <%= link_to "Remove",
                  bookmark_path(b),
                  data: {turbo_method: :delete, turbo_confirm: "Are you sure?"},
                  class: "btn btn-tertiary"
                  %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
    <div class="card m-2">
      <%= render "bookmarks/form", list: @list, status: :created %>
    </div>
  </div>